### Loops

#### The While Loop

In [29]:
company_name = "PiedPiper"
print (len(company_name))
print (0 < 10)
print (10 < 10)

9
True
False


In [31]:
position = 0
lower_case_collector = "" #empty string

while (position < len(company_name)):
    
    if (company_name[position].islower()):
        lower_case_collector += company_name[position]
    else:
        print ("No it was Upper Case")
        
    position += 1

print ("Ok we are outside of the loop")
print (lower_case_collector)

No it was Upper Case
No it was Upper Case
Ok we are outside of the loop
iediper


#### The For Loop

In [34]:
company_name = ("AviaToAA")

for letter in company_name:
    if letter == "A":
        print ("Hey I got an A")
    print (letter)


print ("Ok we are outside of the loop")

Hey I got an A
A
v
i
a
T
o
Hey I got an A
A
Hey I got an A
A
Ok we are outside of the loop


In [4]:
name = "Aviato"
name1 = "avi  ATO."

name2 = name1.replace(" ", "").replace("."," ")
print (name2)


for i in name:
    print (i)
    if i in name1:
        print ("It's also in name1")
    else:
        print ("Didn't find it in name1")


aviATO 
A
It's also in name1
v
It's also in name1
i
It's also in name1
a
It's also in name1
t
Didn't find it in name1
o
Didn't find it in name1


In [3]:
#this is how we import a module
import math
print (math.sqrt(9))

#for bulky ones we can only import what we want
#notice that since we imported directly we don't need the math.
#we can access the function name directly now
from math import sqrt
print (sqrt(9))

#if it has some long and inconvenient name or you use it a lot
#you can rename it
#be aware that there is convention for this
#i.e. for pandas it's pd for numpy it is np
import numpy as np
a = np.arange(12).reshape(3, 4)
print (a)

#however somet things can be n

3.0
3.0
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
#a void function
def got_you_again(times):
    while times < 2:
        print ("We're no strangers to love\n"
               "You know the rules and so do I\n"
               "A full commitment's what I'm thinking of\n"
               "You wouldn't get this from any other guy\n\n"
               "I just want to tell you how I'm feeling\n"
               "Gotta make you understand\n\n"
               "Never gonna give you up, never gonna let you down\n"
               "Never gonna run around and desert you\n"
               "Never gonna make you cry, never gonna say goodbye\n"
               "Never gonna tell a lie and hurt you\n")
        times += 1
    
got_you_again(0)

We're no strangers to love
You know the rules and so do I
A full commitment's what I'm thinking of
You wouldn't get this from any other guy

I just want to tell you how I'm feeling
Gotta make you understand

Never gonna give you up, never gonna let you down
Never gonna run around and desert you
Never gonna make you cry, never gonna say goodbye
Never gonna tell a lie and hurt you

We're no strangers to love
You know the rules and so do I
A full commitment's what I'm thinking of
You wouldn't get this from any other guy

I just want to tell you how I'm feeling
Gotta make you understand

Never gonna give you up, never gonna let you down
Never gonna run around and desert you
Never gonna make you cry, never gonna say goodbye
Never gonna tell a lie and hurt you



In [8]:
#fruitful function or one that returns
def times_2(my_number):
    return my_number * 2

print (times_2(5))

10
